# Generated by Django 3.2.7 on 2021-09-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Наименование')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество')),
                ('measure', models.CharField(choices=[('Штук', 'Штук'), ('Килoгрaмм', 'Килoгрaмм'), ('Литр', 'Литр')], max_length=50, verbose_name='Едицина измерения')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего изменения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
